/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFetchShfeRouteImport } from './routes/api/fetch-shfe'
import { Route as ApiFetchSgeRouteImport } from './routes/api/fetch-sge'
import { Route as ApiFetchFxRouteImport } from './routes/api/fetch-fx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchShfeRoute = ApiFetchShfeRouteImport.update({
  id: '/api/fetch-shfe',
  path: '/api/fetch-shfe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchSgeRoute = ApiFetchSgeRouteImport.update({
  id: '/api/fetch-sge',
  path: '/api/fetch-sge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchFxRoute = ApiFetchFxRouteImport.update({
  id: '/api/fetch-fx',
  path: '/api/fetch-fx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/fetch-fx': typeof ApiFetchFxRoute
  '/api/fetch-sge': typeof ApiFetchSgeRoute
  '/api/fetch-shfe': typeof ApiFetchShfeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/fetch-fx': typeof ApiFetchFxRoute
  '/api/fetch-sge': typeof ApiFetchSgeRoute
  '/api/fetch-shfe': typeof ApiFetchShfeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/fetch-fx': typeof ApiFetchFxRoute
  '/api/fetch-sge': typeof ApiFetchSgeRoute
  '/api/fetch-shfe': typeof ApiFetchShfeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/fetch-fx' | '/api/fetch-sge' | '/api/fetch-shfe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/fetch-fx' | '/api/fetch-sge' | '/api/fetch-shfe'
  id: '__root__' | '/' | '/api/fetch-fx' | '/api/fetch-sge' | '/api/fetch-shfe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFetchFxRoute: typeof ApiFetchFxRoute
  ApiFetchSgeRoute: typeof ApiFetchSgeRoute
  ApiFetchShfeRoute: typeof ApiFetchShfeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-shfe': {
      id: '/api/fetch-shfe'
      path: '/api/fetch-shfe'
      fullPath: '/api/fetch-shfe'
      preLoaderRoute: typeof ApiFetchShfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-sge': {
      id: '/api/fetch-sge'
      path: '/api/fetch-sge'
      fullPath: '/api/fetch-sge'
      preLoaderRoute: typeof ApiFetchSgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-fx': {
      id: '/api/fetch-fx'
      path: '/api/fetch-fx'
      fullPath: '/api/fetch-fx'
      preLoaderRoute: typeof ApiFetchFxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFetchFxRoute: ApiFetchFxRoute,
  ApiFetchSgeRoute: ApiFetchSgeRoute,
  ApiFetchShfeRoute: ApiFetchShfeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
